#!/bin/bash

# Enable Google People API for Firebase Project

echo "🔧 Fixing Google Sign-In - Enable People API"
echo ""
echo "You need to enable the Google People API for your Firebase project."
echo ""

PROJECT_ID="278045186882"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Quick Fix (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click this link (or copy-paste in browser):"
echo ""
echo "https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=${PROJECT_ID}"
echo ""
echo "Then:"
echo "1. Click the 'ENABLE' button"
echo "2. Wait 1-2 minutes for it to activate"
echo "3. Go back to your app and try signing in again"
echo ""
read -p "Press Enter after you've enabled it..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: Manual Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If the link doesn't work, do this manually:"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Select your Firebase project"
echo "3. In the search bar, type: People API"
echo "4. Click on 'Google People API'"
echo "5. Click 'ENABLE'"
echo "6. Wait 1-2 minutes"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test Your App"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After enabling the API:"
echo ""
echo "1. Stop your app (Ctrl+C if running)"
echo "2. Run it again:"
echo "   cd helix-app"
echo "   flutter run"
echo ""
echo "3. Try Google Sign-In again"
echo "4. It should work now! 🎉"
echo ""

echo "✅ Done! Try signing in again."
echo ""
