// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBQoXjWzDxR2wFXS7BvLIQPR5mwaOKN9U',
    appId: '1:459273318088:web:fa166b6cc17a6fb9403ffd',
    messagingSenderId: '459273318088',
    projectId: 'helix-85674',
    authDomain: 'helix-85674.firebaseapp.com',
    storageBucket: 'helix-85674.firebasestorage.app',
    measurementId: 'G-7NY17XMQJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulNSBBVT1FVruUXy8Gu_r7TjKpiEZJ_E',
    appId: '1:459273318088:android:0c8fb2acd125b949403ffd',
    messagingSenderId: '459273318088',
    projectId: 'helix-85674',
    storageBucket: 'helix-85674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWpRCNKXt8OO_KN-iSEMW_zKSA36o49Y',
    appId: '1:459273318088:ios:003be9e5102edff0403ffd',
    messagingSenderId: '459273318088',
    projectId: 'helix-85674',
    storageBucket: 'helix-85674.firebasestorage.app',
    iosClientId: '459273318088-vl8c0igep667ebkhrvdpjdor7l98ai5u.apps.googleusercontent.com',
    iosBundleId: 'com.helix.helix',
  );
}
